# Generated by Django 5.0.6 on 2024-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Name of User"
            ),
            preserve_default=False,
        ),
    ]
