# Generated by Django 5.0.6 on 2024-07-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_price_alter_product_quantity_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="owner",
        ),
    ]
