# Generated by Django 5.0.6 on 2024-07-02 10:21

import django.utils.timezone
import drugstoc_inventory.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_rename_user_order_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="active"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.CharField(
                default=drugstoc_inventory.model_utils.generate_id,
                editable=False,
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
