# Generated by Django 5.0.6 on 2024-07-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_orderitem_options_orderitem_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="total_quantity",
        ),
    ]
