# Generated by Django 5.0.6 on 2024-07-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_orderitem_price_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
    ]
